### ISSUE TITLE
Align cookie design to Micro:bit Foundation one

### ISSUE THREAD

**Issue by micque01** [microbit-foundation/ml-trainer#4]
Change the design of the cookie popup to align with the Micro:bit Foundation one:

![Image](https://github.com/microbit-foundation/ml-trainer/assets/11059840/d4fe0980-e1d2-44a8-9c23-0254a822143c)

**Comment by microbit-matt-hillsdon** [comment]
This was done by https://github.com/microbit-foundation/ml-trainer/pull/37
