### ISSUE TITLE
Issue with Windows High Contrast mode

### ISSUE THREAD

**Issue by kmcnaught** [microbit-foundation/ml-trainer#509]
According to [WebAIM’s 2018 “Survey of Users with low Vision”](https://webaim.org/projects/lowvisionsurvey2/#contrastMode), more than 50% of the low vision users use some kind of High Contrast Mode.

On Windows there is an OS-level [Windows High Contrast mode (WHCM)](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/) which can be detected via `forced-colors`. 

In general the CreateAI web app adapts really well, with 2 exceptions. 

Example of 1 of 3 "dark mode" themes:
![Example photo of dark mode high contrast](https://github.com/user-attachments/assets/ca2d6485-ff33-491b-bd6f-f73c40ee5b89)

Example of 1 of 1 "light mode" theme:
![Example photo of light mode high contrast](https://github.com/user-attachments/assets/637cb5d3-3de6-4652-9602-5d48df13a837)

### Buttons

In the first example, the "home", "settings" and "(?)" buttons are not visible. 
In the second example, the "hamburger" button is not visible. 
Note that in both examples, the "(i)" buttons (tooltips) are visible. 

Is there something in how the different buttons are defined that can be changed, so they all respect the contrast settings?

### Graph colours

The "dark mode" versions of WHCM obviously flip our expectations of the graph colours. How best to fix?
- another option in the colour themes? inverted? 
- detect `forced-colors` and partially override colour themes? e.g. if we knew it was dark mode, then we could make the blue of RGB much lighter, and the black of the colourblind themes could turn to white. But I'm not sure if we could be sure of this? It would be a likely conclusion of `forced-colors` && `[prefers-](prefers-color-scheme: dark)` but that feels a bit hacky.

**Comment by microbit-robert** [comment]
Update accessibility statement when this issue is resolved.
