### ISSUE TITLE
Info tooltips are not navigable with keyboard

### ISSUE THREAD

**Issue by kmcnaught** [microbit-foundation/ml-trainer#519]
Parking this issue here - happy to write up, or dump existing email conversations, but just want to mark its place in the pile of issues here on github. Not sure if you've already taken any action in any of the discussed directions.

**Comment by microbit-robert** [comment]
See https://github.com/microbit-foundation/ml-trainer/pull/526

**Comment by microbit-matt-hillsdon** [comment]
Now navigable with the keyboard. We might need to revisit tooltips for screenreader and the idea that moving towards the content shouldn't dismiss it but let's track via the report/other issues.

**Comment by kmcnaught** [comment]
To confirm that this still doesn't make the tooltip content accessible with NVDA. It appears the tooltip has `aria-describedby` but only _after_ clicking on it / tabbing to it. Should this be present from page load?

**Comment by kmcnaught** [comment]
(but still an improvement re keyboard accessibility, thanks :)
