### ISSUE TITLE
Update video on front page

### ISSUE THREAD

**Issue by micque01** [microbit-foundation/ml-trainer#54]
Video on front page needs updating to the new one (which should be on Youtube). Link to come...

**Comment by microbit-lucy** [comment]
Update to YouTube embed - rip off how the Python editor does it on the Welcome dialogue. 
Just use any micro:bit video for now as a placeholder.

**Comment by microbit-matt-hillsdon** [comment]
Switched to YouTube embed with placeholder. Final video tracked in Monday.
