### ISSUE TITLE
"Your micro:bit firmware is outdated" message

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/ml-trainer#55]
We need to figure out what triggers this warning.

We also need to update the wording, as we use the word "firmware" only for DAPLink, and I believe this refers to the programmed loaded in the micro:bit with the BLE services.

https://github.com/microbit-foundation/ml-trainer/blob/fa07240d460788d3028da8ebb6efd9f6b0d20551/public/firmware/dev/README.md#L7-L8

**Comment by microbit-matt-hillsdon** [comment]
It's using it in multiple tabs I think.

Now tracked by https://microbit-global.monday.com/boards/1356069004/pulses/1356472449 which has some more detail and a text update PR.
